# Generated by Django 3.2.5 on 2021-08-01 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_search', '0009_alter_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciality',
            name='picture',
            field=models.ImageField(upload_to='speciality_images'),
        ),
    ]
