# Generated by Django 3.2.5 on 2021-08-01 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_search', '0010_alter_speciality_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='written_username',
            field=models.CharField(max_length=100, verbose_name='123'),
        ),
    ]
